# Generated by Django 4.2.6 on 2023-10-08 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_sync', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testparticipant',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='username',
            new_name='user_id',
        ),
    ]
